# Generated by Django 5.2.9 on 2025-12-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
